language: ruby
bundler_args: "--without production"
env:
  global:
    - CC_TEST_REPORTER_ID=f6678f154a744f1cea9cf52a972f49be81fe2783f2affc17f4e7ecd5c1727892
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
stages:
- test
- deploy
jobs:
  include:
    - stage: deploy
      install: skip  # no tests, no depedencies needed
      script: skip  # we're not running tests
      deploy:
        provider: heroku
        app: fast-cove-84745
        run: "rails db:migrate"
        api_key:
          secure: m+n4/byckOpOqYhmwVi2AYwEFbabJOAzCzQeZAbz32lGerCHcsTXB/rsV+7TAHpfF5LawFXU3mfb7ssoMKa/1vZTmBZoR6uP9APc9WJemMC9XJIPkC11RFjrKU1UOsPzjkW/f2q362A6lNS8XXrE93tRBQpeErIXbniklA+ATqmN1O4tbXFFFJoZDl9h1rZPw3ubClQrtAr8JxI0R3HrCqoonrQAWbyyFWm7+mWlx9KIdj9pkEwBebwbNjC5ulmPyEjVSh9vMyikfExNS4oLnRwpP8P1TQhxMxQ/2icYxBdbhUyHBry/pGS1rycy84/5ox2qL50eoW+DzE3B8swwOLKnTvR0Q7UxxYOBom9ZuLF77O5bberOfSr3p0SmFpFKk8E9mpCdlhyqPxvzb1DvZFV0JXPqtnTKoP/Sw1swlVL1byfZNFTaxBcVpQ6rO4WOySy3zoliDBKyWlWsQowlXE6gZwYF3BAumtu/pnDQ/tM8Zldl9nM2lGp9HLJr5EKq0hkMjTuFCKLjJmO3fhgfnXdp84oHFx0rpgKDTaPJyWoF6A5hShGhqiXpbuLoNtVqbZwvWmxaasbnKt82RywpKF3uwI0jloGwwlAUJQA4amMNFx3m4dAFNyJHleA04ZWl6FVKTca4iGGXyGZlzm4ksAl0o5XZ5i2lmo7gdKK5iIo=
