City.create!(name: 'San Francisco', timezone: 'America/Los_Angeles')
City.create!(name: 'Seattle', timezone: 'America/Los_Angeles')
City.create!(name: 'Austin', timezone: 'America/Chicago')
City.create!(name: 'Toronto', timezone: 'America/New_York')
City.create!(name: 'New York', timezone: 'America/New_York')
City.create!(name: 'Las Vegas', timezone: 'America/Los_Angeles')
City.create!(name: 'Boston', timezone: 'America/New_York')